version: '3.8'

services:
  backend:
    build:
      context: ./qualite
      dockerfile: Dockerfile
    container_name: contratq_backend_prod
    restart: unless-stopped
    ports:
      - "7623:7623" 
    environment:
      # N'forciw l'Backend y-accepter les fichiers kbar mn Docker env
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB
    deploy:
      resources:
        limits:
          memory: 1G 
    networks:
      - contratq-network

  frontend:
    build:
      context: ./qualite-frontend
      dockerfile: Dockerfile
      args:
        # Hna katji l'valeur dynamique mn Jenkins
        - NEXT_PUBLIC_API_URL=${API_URL:-http://localhost:7623}
    container_name: contratq_frontend_prod
    restart: unless-stopped
    ports:
      # Port jdid w b3id 3la 3000
      - "8741:8741"
    environment:
      - PORT=8741
    depends_on:
      - backend
    networks:
      - contratq-network

networks:
  contratq-network:
    driver: bridge