version: '3.8'

services:
  # 1. BASE DE DONNÉES (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: contratq_postgres_prod
    restart: always
    environment:
      # Docker ghay-creer had DB w l'User oumatiquement f l'awel lancement
      - POSTGRES_DB=contratQualite
      - POSTGRES_USER=kyntus_user
      - POSTGRES_PASSWORD=kyntus_password
    ports:
      - "5432:5432"
    volumes:
      # 🛡️ RISK MANAGEMENT: Hada hwa l'coffre-fort. Data ghat-b9a hna wakha t-msse7 l'container
      - postgres_data:/var/lib/postgresql/data
    networks:
      - contratq-network

  # 2. BACKEND (Spring Boot)
  backend:
    build:
      context: ./qualite
      dockerfile: Dockerfile
    container_name: contratq_backend_prod
    restart: always
    ports:
      - "7623:7623" 
    environment:
      # L'Backend ghay-hder m3a l'container 'db' f nfs l'réseau Docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/contratQualite
      - SPRING_DATASOURCE_USERNAME=kyntus_user
      - SPRING_DATASOURCE_PASSWORD=kyntus_password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 1.5G 
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - contratq-network

  # 3. FRONTEND (Next.js)
  frontend:
    build:
      context: ./qualite-frontend
      dockerfile: Dockerfile
      args:
        # L'Navigateur ghay-hder m3a l'IP d l'serveur
        - NEXT_PUBLIC_API_URL=http://10.10.10.25:7623
    container_name: contratq_frontend_prod
    restart: always
    ports:
      - "8741:8741"
    environment:
      - PORT=8741
    depends_on:
      - backend
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - contratq-network

# Déclaration dyal l'Volume w l'Réseau
volumes:
  postgres_data:

networks:
  contratq-network:
    driver: bridge