# ===============================
# DATABASE CONFIGURATION (Hybrid: Local + Docker/Prod)
# ===============================
# Logic: "Chouf l ENV variable, ila mal9itihach, khdem b localhost + Turbo Batching"
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/qualite_db?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:waeloujdiastral481123456}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings
spring.datasource.hikari.maximum-pool-size=30

# ===============================
# HIBERNATE & JPA
# ===============================
# Create/Update tables automatically
spring.jpa.hibernate.ddl-auto=update
# Explicit Dialect (Bach Spring ye3ref rah khdam m3a Postgres)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# LOGS & PERFORMANCE OPTIMIZATION
# ===============================
# Khasshom ykouno false w ERROR bach ma y-crashich l PC f les grands fichiers
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR

# Disable Migration Tools (Flyway & Liquibase) ????? hta n7tajouhom
spring.flyway.enabled=false
spring.liquibase.enabled=false

# ===============================
# SERVER CONFIGURATION
# ===============================
# Port standard dialek f 8082, avec variable d env au cas ou
server.port=${SERVER_PORT:7623}

# ===============================
# MULTIPART / UPLOAD LIMITS
# ===============================
# THE MASTER FIX: N-kebbrou l-m3ida d' Spring Boot f' Local l 500MB
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Tomcat connection optimizations dial kyntus os
server.tomcat.connection-timeout=120000
server.tomcat.max-threads=50
server.tomcat.accept-count=100