spring.application.name=qualite

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://10.10.10.50:5432/contratQualite?reWriteBatchedInserts=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:waeloujdiastral481123456}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=30

# ===============================
# HIBERNATE & JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR

spring.flyway.enabled=false
spring.liquibase.enabled=false

# ===============================
# SERVER CONFIGURATION
# ===============================
server.port=${SERVER_PORT:7623}

# ===============================
# MULTIPART / UPLOAD LIMITS
# ===============================
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.connection-timeout=120000
server.tomcat.max-threads=50
server.tomcat.accept-count=100